exemplo: 
SUCESSO: 

// TESTANDO SE NAO RETORNOU ERRO DE EXCESAO NA CRIACAO 
    // SUCESSO:: ESPERO QUE A RESOLUCAO DA PROMESSA NAO DISPARE NENHUM ERRO
    await expect(createProdEncomenda.execute({ nome: 'prod_encomenda_01', preco: 15 }))
    .resolves
    .not
    .toThrow()



wait expect(inMemoryPrismaProdEncomendaRepository.items).toEqual(expect.arrayContaining([
    expect.objectContaining({
      nome: 'prod_encomenda_01', preco: 15  
    })

    /*
    - FUI NA VARIAVEL DO ARRAY : expect(inMemoryPrismaProdEncomendaRepository.items)
    - FUI DENTRO DO ARRAY :: .toEqual(expect.arrayContaining([

    - VERIFIQUEI SE LA DENTRO FOI CRIADO O OBJETO COM OS DADOS IGUAIS DA CRIACAO ::
    expect.objectContaining({
      nome: 'prod_encomenda_01', preco: 15  
    })

    */

    ---

    FALHA ::
    await expect(createProdEncomenda.execute({ nome: '', preco: 15 }))
    .rejects
    .toThrow()

    // É PRA FALHAR - ENTÃO CAPTURO COM REJECTS -- ESPERO QUE MEU ARRAY ESTEJA VAZIO SE O NOME NÃO FOR IGUAL OA PASSADO -- É PRA NAO CRIAR NADA

   expect(inMemoryPrismaProdEncomendaRepository.items).toEqual(expect.arrayContaining([ ]))

  }) // 
  